#!/bin/bash
#
#Vanuse määramine

echo -n "Sisesta oma vanus:"
read vanus

if [ $vanus -gt 0 -a $vanus -lt 11 ]; then
	echo "oled laps"
else #if within if within 
	if [ $vanus -ge 11 -a $vanus -lt 18 ]; then
		echo "oled nooruk"
else
	if [ $vanus -ge 18 -a $vanus -lt 63 ]; then
		echo "oled täiskasvanu"
else 
	if [ $vanus -ge 63 ]; then
		echo "oled senjoor"
	else
		echo "Vigane sisestus"
			fi
		fi
	fi
fi

#skripti lõpp 
