#!/bin/bash
#Arvu paarsuse arvutamise skript
#
# Küsime kasutaja käest arvu
echo -n "Sisesta suvaline täisarv: "
read arv
# kontrollime, kas antud arv on paaris
jaak=$(( $arv % 2 ))
# kui jaak on 0 - on tegu paaris arvuga
if [ $jaak -eq 0 ]
then
	echo "Antud arv on paaris"
else
	echo "Antud arv on paaritu"

fi # if lause lõpp
echo "--------------------"
#skripti lõpp
