#!/bin/bash
# busside arvu arvutamine
#
echo -n "Sisesta reisijate arv:"
read reisijate_arv
#
echo -n "Sisesta kohtate arv bussis:"
read kohtade_arv_bussis
#
busside_arv=$(($reisijate_arv / $kohtade_arv_bussis))
ei_mahtunud=$(($reisijate_arv % $kohtade_arv_bussis))
#kui ei_mahtunud on suurem kui 0
#siis suurendame busside_arv 1 võrra
if [ $ei_mahtunud -gt 0 ]; then
	busside_arv=$(($busside_arv + 1))
fi
# trükime vastuse
echo "kokku läheb vaja $busside_arv bussi"
