#!/bin/bash

#Kuu numbrile tuleb väljastada kuu nimetus

echo -n "Sisesta kuu number:"
read kuu

case $kuu  in
	"1" ) echo "See on jaanuar";;
	"2" ) echo "See on veebruar";;
	"3" ) echo "See on märts, jube vilets see aasta";;
	"4" ) echo "See on aprill";;
	"5" ) echo "See on mai, kõige parem kuu ";;	
	"6" ) echo "See on juuni";;
	"7" ) echo "See on juuli";;
	"8" ) echo "See on august";;
	"9" ) echo "See on september, tagasi kooli marss!";;
	"10" ) echo "See on oktoober";;
	"11" ) echo "See on november";;
	"12" ) echo "See on detsember";;
*) echo "Vigane sisend, kuu numbrid on ju 1-st 12-ni, try again!"
esac
