#!/bin/bash

date +"Today is %A, %B %m, %Y" # see command postitab täiesõnalsielt päeva, kuu ja pikemalt aasta
date +"Time is %R"  #see command postitab praeguse aja
echo ""
echo -n "Calendar of"
cal  # see command postitab kalendri
