#!/bin/bash
#
#
Pyhapaev=0
Esmaspaev=1
Teisipaev=2
Kolmapaev=3
Neljapaev=4
Reede=5
Laupaev=6
#
echo -n "Sisesta millal sõidad ära":
read a
echo -n "Sisesta reisi ööpaevade arv":
read b

#Reisimise täisnadalate arv ja kui reisipäevi jääb üle
c=$(($b % 7))
#Tagasi jõuad
d=$(($a + $c))
echo  "Tagasi oled päeval number:$d "

