#!/bin/bash
#
#tervitusskript
#
echo -n "Tere,"  # väljastab ilma reavahetusteta Tere,
echo -n `who am i | cut -c1 | tr [:lower:] [:upper:]` #väljastab esimese tähe ja muudab suureks
echo -n `who am i | cut -c2-` #lõika kõik tähed alates 2-st
echo "!"
#
# skripti lõpp
