#!/bin/bash
#
#Koostada script, mis väljastab nime,grupi, arvamus õppivast ainest
#
echo "Margus Noppel"        #väljastab nime
echo "IS117"                #väljasab grupi
echo "Aine tundub väga põnev ja huvitav" #väljastab esmamulje
echo "Sattusin probleemi otsa, mis käis närvidele, aga selle likvideermisega sain palju targemaks käskude osas" #väljastab praeguse mulje ja edasijõudmine
#
# skripti lõpp
