#!/bin/bash

# Sisseehitatud tärni tsükkel

for (( i = 1; i <= 5; i++))  ### Outer for loop ###
do
	echo -n "$i."
	for (( j = 1 ; j <= 5; j++ )) ### Innerfor loop"
	do 
		echo -n "*"
	done
	echo "" ### print the new line ###
	done
