#!/bin/bash

# tärni tsükkel kolmnurk tagurpidi

echo "Sisesta ridade arv:"
read rida


echo ""
for (( i = 1; i <= $rida; i++))  ### Välitsükkel ###
do
	echo -n "$i."
	for (( j = $rida ; j >= i; j-- )) ### Sisetsükkel"
	do 
		echo -n "* "
	done
	echo "" ### print the new line ###
	done #we're done here *drops mic*
